### ISSUE TITLE
Can I prevent auto scroll top?

### ISSUE THREAD

**Issue by saphira177** [HaidarZ/ng-mat-select-infinite-scroll#10]
Hi @HaidarZ , when I scroll down to the bottom and getNextBatch is triggered, the list items are scrolled automatically to top. How can I prevent this action?
I’m using version 2.0.0 with angular 8.
Another issue is that the demo page on stackblitz is not working

**Comment by HaidarZ** [comment]
Hi @saphira177 , I wasn't able to replicate your issue , maybe it's related to the original angular material.
I fixed the issue related to stackblitz  ;)

**Comment by saphira177** [comment]
Hi @HaidarZ , thank you for fixing demo on stackblitz. This issue doesn't appear on that site, so it doesn't belong to your library.
I will close this issue.

**Comment by jvinhit** [comment]
@HaidarZ please give me stackblitz, thanks !
