### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by L-NiNo** [HaidarZ/ng-mat-select-infinite-scroll#13]
While upgrading to Angular 10, the material dependency in this package fails. 

![image](https://user-images.githubusercontent.com/34686592/89682021-a3fd6c80-d8bb-11ea-96cf-8323443828d2.png)

I forced the material update. For my use cases of this package, I do not seem to have any issues aside from the install failure.

**Comment by HaidarZ** [comment]
I've released a new version of the library version 2.1.0 , kindly update your dependencies and get back to me :)

**Comment by L-NiNo** [comment]
update to latest and warning in the install is gone. Thanks!
