### ISSUE TITLE
missing exported member when building application

### ISSUE THREAD

**Issue by andreastauboeck** [HaidarZ/ng-mat-select-infinite-scroll#22]
I'm getting the following error message when building my application after adding infinite scrolling:

```
Error: node_modules/ng-mat-select-infinite-scroll/lib/mat-select-infinite-scroll.module.d.ts:7:21 - error TS2694: Namespa
ce '"C:/terrazo_webui/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

7     static ɵinj: i0.ɵɵInjectorDeclaration<MatSelectInfiniteScrollModule>;
                      ~~~~~~~~~~~~~~~~~~~~~

```

There are some other Errors like that.

I use these versions so it should work:

    "@angular/cdk": "^11.2.0",
    "@angular/core": "^11.2.0",
    "@angular/material": "^11.2.0",
    "rxjs": "^6.6.3",

Someone experienced this issue already?

**Comment by njgarcia** [comment]
Is there any update on this? I'm getting the same error, didn't find any solution

**Comment by vagnersabadi** [comment]
Until version 2.1.1 is working without errors in the console

**Comment by HaidarZ** [comment]
Hello guys,
Can you please share me your environment and a sample project so that I can replicate the issue.

**Comment by simetelum** [comment]
I changed import 
from:
{ MatSelectInfiniteScrollModule } from "ng-mat-select-infinite-scroll/lib/mat-select-infinite-scroll.module";
to:
import { MatSelectInfiniteScrollModule } from "ng-mat-select-infinite-scroll";

and it worked!

**Comment by jameskaye** [comment]
I had to go from angular 11 to 12 to fix this
