### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by samtstern** [HaidarZ/ng-mat-select-infinite-scroll#27]
This repo currently has no LICENSE, which is preventing us from listing it on https://devlibrary.withgoogle.com/ (and generally preventing people from using it confidently)

**Comment by HaidarZ** [comment]
It's MIT licensed , kindly check [LICENSE](https://github.com/HaidarZ/ng-mat-select-infinite-scroll/blob/master/LICENSE)

**Comment by samtstern** [comment]
Sorry this was my mistake, must be a bug in my logs!
