### ISSUE TITLE
Module is not installing with Azure Pipelines after the update version 1.2.0 is released on npm.

### ISSUE THREAD

**Issue by sethi-ishmeet** [HaidarZ/ng-mat-select-infinite-scroll#4]
After this library was updated on npmjs.org yesterday, it is not being installed in our CI process and we're getting the error - `Cannot find module 'ng-mat-select-infinite-scroll'`.

**Comment by HaidarZ** [comment]
Did you update your `package-lock.json` file ?
Most probably you must apply `npm install` on your local project in order for `package-lock.json` to be updated then push it to the remote repository. 
That's the behavior of `npm ci`

https://docs.npmjs.com/cli/ci.html
> - If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock.

**Comment by sethi-ishmeet** [comment]
This is also the problem with localhost when I reinstall this package. It wasn't a problem ever before this udpate.

**Comment by HaidarZ** [comment]
I'll checkout the issue :/

**Comment by sethi-ishmeet** [comment]
I deleted my `node_modules/` folder and `package-lock.json` file but the issue still persists.

**Comment by HaidarZ** [comment]
I've released a new bug fix (v1.2.1). There was an issue with github actions workflow.

**Comment by sethi-ishmeet** [comment]
Great.` v1.2.1` works fine. The problem was with `1.2.0`. Even 1.1.0 worked fine.
