### ISSUE TITLE
Will there be support for Angular 9?

### ISSUE THREAD

**Issue by ArsalanSavand** [HaidarZ/ng-mat-select-infinite-scroll#8]

**Comment by HaidarZ** [comment]
I've initialized support for Angular 9 in version 1.3.0. 
Would you please try it out and give me your feedback ! :)

**Comment by ArsalanSavand** [comment]
@HaidarZ Sorry for the late response. I'm currently working on Angular 8 projects and I wanted to know if I install this package, will it cause any version compatibility issues or not.

Thank you for letting me know.
